# Math operations in TensorFlow

We will explore some of the math operations in Tensorflow using Eager execution mode. 

In [1]:
import warnings
warnings.filterwarnings('ignore')

import tensorflow as tf
tf.logging.set_verbosity(tf.logging.ERROR)

Enable Eage Execution mode:

In [2]:
tf.enable_eager_execution()

Define x and y:

In [3]:
x = tf.constant([1., 2., 3.])
y = tf.constant([3., 2., 1.])

## Basic Operations

#### Addition

In [4]:
sum = tf.add(x,y)
sum.numpy()

array([4., 4., 4.], dtype=float32)

#### Subtraction

In [5]:
difference = tf.subtract(x,y)
difference.numpy()

array([-2.,  0.,  2.], dtype=float32)

#### Multiplication

In [6]:
product = tf.multiply(x,y)
product.numpy()

array([3., 4., 3.], dtype=float32)

#### Division

In [7]:
division = tf.divide(x,y)
division.numpy()

array([0.33333334, 1.        , 3.        ], dtype=float32)

#### Square

In [8]:
square = tf.square(x)
square.numpy()

array([1., 4., 9.], dtype=float32)

#### Dot Product

In [9]:
dot_product = tf.reduce_sum(tf.multiply(x, y))

dot_product.numpy()

10.0

## Finding the index of min and max element

In [10]:
x = tf.constant([10, 0, 13, 9])

Index of minimum value:

In [11]:
tf.argmin(x).numpy()

1

Index of maximum value:

In [12]:
tf.argmax(x).numpy()

2

### Squared Difference 

In [13]:
x = tf.Variable([1,3,5,7,11])
y = tf.Variable([1])

tf.math.squared_difference(x,y).numpy()

array([  0,   4,  16,  36, 100], dtype=int32)

### Power

x^x

In [14]:
x = tf.Variable([1,2,3,4])
tf.pow(x, x).numpy()

array([  1,   4,  27, 256], dtype=int32)

## Rank of the matrix

In [15]:
x = tf.constant([[[1,2,4],[3,4,5]],
             [[1,2,4],[3,4,5]]])

x.shape

TensorShape([Dimension(2), Dimension(2), Dimension(3)])

In [16]:
x.numpy()

array([[[1, 2, 4],
        [3, 4, 5]],

       [[1, 2, 4],
        [3, 4, 5]]], dtype=int32)

## Reshape the matrix

In [17]:
x = tf.constant([[1,2,3,4], [5,6,7,8]])

In [18]:
tf.reshape(x,[8,1]).numpy()

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]], dtype=int32)

## Transpose the matrix

In [19]:
tf.transpose(x)

<tf.Tensor: id=60, shape=(4, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]], dtype=int32)>

## Typecasting 

In [20]:
x.dtype

tf.int32

In [21]:
x = tf.cast(x, dtype=tf.float32)

x.dtype

tf.float32

## Concatenating two matrices

In [22]:
x = [[3,6,9], [7,7,7]]
y = [[4,5,6], [5,5,5]]

Concatenate row-wise:

In [23]:
tf.concat([x, y], 0).numpy()

array([[3, 6, 9],
       [7, 7, 7],
       [4, 5, 6],
       [5, 5, 5]], dtype=int32)

Concatenate column-wise:

In [24]:
tf.concat([x, y], 1).numpy()

array([[3, 6, 9, 4, 5, 6],
       [7, 7, 7, 5, 5, 5]], dtype=int32)

Stack x matrix:

In [25]:
tf.stack(x, axis=1).numpy()

array([[3, 7],
       [6, 7],
       [9, 7]], dtype=int32)

## Reduce Mean

In [26]:
x = tf.Variable([[1.0, 5.0], [2.0, 3.0]])

In [27]:
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

Compute average values i.e (1.0 + 5.0 + 2.0 + 3.0) / 4

In [28]:
tf.reduce_mean(input_tensor=x).numpy() 

2.75

Average across the row i.e, [ (1.0+5.0)/2, (2.0+3.0)/2]

In [29]:
tf.reduce_mean(input_tensor=x, axis=0).numpy() 

array([1.5, 4. ], dtype=float32)

Average across the column i.e [(1.0+5.0)/2.0, (2.0+3.0)/2.0]

In [30]:
tf.reduce_mean(input_tensor=x, axis=1, keepdims=True).numpy()

array([[3. ],
       [2.5]], dtype=float32)

## Reduce Sum

In [31]:
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

Sum values across the rows i.e  [(1.0+2.0),(5.0 + 3.0)]

In [32]:
tf.reduce_sum(x, 0).numpy()

array([3., 8.], dtype=float32)

Sum values across the columns i.e  [(1.0+5.0),(2.0 + 3.0)]

In [33]:
tf.reduce_sum(x, 1).numpy()

array([6., 5.], dtype=float32)

Sum all the values i.e 1.0 + 5.0 + 2.0 + 3.0

In [34]:
tf.reduce_sum(x, [0, 1]).numpy()

11.0

## Drawing Random values

Drawing values from the normal distribution:

In [35]:
tf.random.normal(shape=(3,2), mean=10.0, stddev=2.0).numpy()

array([[ 9.965095,  8.426764],
       [10.50976 ,  9.429149],
       [11.404266,  7.635334]], dtype=float32)

Drawing values from the uniform distribution:

In [36]:
tf.random.uniform(shape = (3,2),  minval=0, maxval=None, dtype=tf.float32,).numpy()

array([[0.1445148 , 0.13028955],
       [0.8927735 , 0.89294124],
       [0.65974724, 0.7600925 ]], dtype=float32)

## Create 0's and 1's

In [37]:
tf.zeros([5,5]).numpy()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)

In [38]:
tf.zeros_like(x).numpy()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [39]:
tf.ones([5,5]).numpy()

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [40]:
tf.ones_like(x).numpy()

array([[1., 1.],
       [1., 1.]], dtype=float32)

## Compute Softmax Probabilities

In [41]:
x = tf.constant([7., 2., 5.])

tf.nn.softmax(x).numpy()

array([0.8756006 , 0.00589975, 0.11849965], dtype=float32)

## Create Indentity matrix

In [42]:
i_matrix = tf.eye(7)
print i_matrix.numpy()

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


## L2 Normalization

In [43]:
tf.math.l2_normalize(x,axis=None, epsilon=1e-12,).numpy()

array([0.79259396, 0.22645542, 0.56613857], dtype=float32)

## Gradient Computation

In [44]:
def square(x):
  return tf.multiply(x, x)

with tf.GradientTape(persistent=True) as tape:
     print square(6.).numpy()


36.0


TensorFlow is a lot more than this. We will learn and explore various important functionalities of TensorFlow as we move forward through the book. In the next section, we will learn about a new version of TensorFlow called TensorFlow 2.0.